## Numpy
numpy is a fundalmental library for scientific computing in python. It provides support for arrays and matrices , along with a collectionof mathematical fxns to operate on these data structures. 


In [ ]:
!pip install numpy       # to install numpy package

In [3]:
import numpy as np        # import numpy package with alias np

## create array using numpy 
## create a 1 d array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1)) 
print(arr1.shape)  # it tells dimension as it is single dimension (now row col thing until we reshap like below to say it )



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)              # here we saying as 1 row and 5 col that's why two [[]] means two dimension

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [5]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))    # to create array of 3 X 4 with all elements=1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array 

arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)  # output dimension
print("Number of dimensions:",arr.ndim) 
print("size (number of elements):",arr.size)
print("Datatype:",arr.dtype) 
print("Item size (in bytes)",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
size (number of elements): 6
Datatype: int64
Item size (in bytes) 8


In [10]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition: ",arr1+arr2)

## Element wise substraction
print("Substraction: ",arr1-arr2)

# Element wise multiplication
print("Multiplication:",arr1*arr2)

# Element wise division
print("Division:",arr1/arr2)



Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [11]:
## Universal fxn
arr=np.array([2,3,4,5,6])

## sqr root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
## array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array: \n",arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
# accessing
print(arr[0][0]) 

print(arr[0:2,1:])     # row ka 0 to <2 and col mai 1 ke baad


1
[[2 3 4]
 [6 7 8]]


In [ ]:
arr[1:]    # 1st row sai end tak ki

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr[1:,2:]   # second col ke baad 

array([[ 7,  8],
       [11, 12]])

In [ ]:
## listen two ways of writing
  arr[0][0]           is same as  arr[0,0]



In [29]:
## Modify array elements 
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
### Statistical concepts  -- Normalization
## normailzation means cnvrting data to have a mean of 0 and standard deviation of 1

data= np.array([1,2,3,4,5])

# calici the mean and standrd deviation
mean = np.mean(data)
std_dev=np.std(data)

# Normalize the data
normalized_data= (data - mean)/std_dev
print("Normalized data:",normalized_data)




Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean= np.mean(data)
print("Mean:",mean)

#Median
median=np.median(data)
print("Median:",median)

# Standard Deviation
std_dev= np.std(data)
print("standard Deviation:",std_dev)

# Variance
variance=np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
standard Deviation: 2.8722813232690143
Variance: 8.25


In [32]:
# Logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [34]:
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])